/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/S3drVLSoA0D
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Eczar } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

eczar({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import React, { useState, useEffect, useRef, SVGProps} from "react"
import Image from 'next/image';
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, DialogClose } from "@/components/ui/dialog"
import Navbar from '../component/navbar'; // Adjust the path as needed
import BackToTopButton from '../component/BackToTopButton'; // Adjust the path as needed
import { MailIcon, PhoneIcon } from "lucide-react"
import { saveAs } from 'file-saver'; // FileSaver.js for file downloads
import emailjs from '@emailjs/browser';
import Loader from '../component/loader';
import WhyChooseUs from '../component/WhyChooseUs';
import WhatsAppFloatingIcon from "./WhatsAppFloatingIcon";
// import WhatsAppFloatingIcon from '../component/WhatsAppFloatingIcon';




type FormValues = {
  name: string;
  email: string;
  mobileNumber: string;
};

type FormdValues = {
  mobiledNumber: string;
};


export function Home1() {
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [isLoading, setIsLoading] = useState(false);
  const initialValues: FormValues = { name: "", email: "", mobileNumber: "" };
  const [formValues, setFormValues] = useState(initialValues);

  const initialdValues: FormdValues = { mobiledNumber: "" };
  const [formdValues, setFormdValues] = useState(initialdValues);
  const [formdErrors, setFormdErrors] = useState<{ [key: string]: string }>({});

  const [formErrors, setFormErrors] = useState<{ [key: string]: string }>({});
  const [isSubmit, setIsSubmit] = useState(false);
  const [isSubmitd, setIsSubmitd] = useState(false);

  const form = useRef<HTMLFormElement | null>(null);
  
  const sendEmail = () => {
    if (form.current) {
      console.log(form.current)
      emailjs.sendForm('YOUR_SERVICE_ID', 'YOUR_TEMPLATE_ID', form.current, 'YOUR_USER_ID')
        .then(() => {
          console.log('SUCCESS!');
        }, (error) => {
          console.log('FAILED...', error.text);
        });
    } else {
      console.error('Form reference is null');
    }
  };
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormValues({ ...formValues, [name]: value });
  };


  const handledChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormdValues({ ...formdValues, [name]: value });
  };


  const handleSubmit: React.FormEventHandler<HTMLFormElement> = async (e) => {
    e.preventDefault();
    setIsLoading(true);

    // Validate form values
    const errors = validate(formValues);
    setFormErrors(errors);

    if (Object.keys(errors).length === 0) {
      try {
        // Simulate async operation (e.g., API call or file download)
        // const pdfUrl = "/brochure1.pdf";

        if (form.current) {

          await emailjs.sendForm('service_zxqe3ql', 'template_8aizoix', form.current, 'YPGH4Bt3T7bZH8HLb');
          console.log('SUCCESS!');
             // Simulate a delay for demonstration purposes
            await new Promise(resolve => setTimeout(resolve, 1000));

            // Save the brochure as a file
            // saveAs(pdfUrl, 'brochure.pdf');

            // Reset form values
            setFormValues({ name: '', email: '', mobileNumber: '' });

            // Optionally, show success notification
            // Close the modal if applicable
        }

      } catch (error) {
        console.error("Failed to process the form", error);
        // Handle error state if needed
      }
    }
    setIsLoading(false);
  };


  useEffect(() => {
    console.log(formErrors);
    if (Object.keys(formErrors).length === 0 && isSubmit) {
      // console.log(formValues);
    }

  }, [formErrors, isSubmit]);


  useEffect(() => {
    console.log(formdErrors);
    if (Object.keys(formdErrors).length === 0 && isSubmitd) {
      // console.log(formdValues, isSubmitd);
    }
    
  }, [formdErrors, isSubmitd]);

  const validate = (values: typeof formValues) => {
    const errors: typeof formErrors = {};
    const regexEmail = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i;
    const regexPhone = /^(\+91[\-\s]?|91[\-\s]?|0)?[789]\d{9}$/;

    if (!values.name) errors.name = "Name is required!";
    if (!values.email) errors.email = "Email is required!";
    else if (!regexEmail.test(values.email)) errors.email = "Invalid email format!";
    if (!values.mobileNumber) errors.mobileNumber = "Mobile number is required!";
    else if (!regexPhone.test(values.mobileNumber)) errors.mobileNumber = "Invalid mobile number format!";
    
    return errors;
  };

  const validated = (values: FormdValues) => {
    const errors: { [key: string]: string } = {};
    const regexM  = /^(\+91[\-\s]?|91[\-\s]?|0)?[789]\d{9}$/

    if (!values.mobiledNumber) {
      errors.mobiledNumber = "mobileNumber is required!";
    } else if (!regexM.test(values.mobiledNumber)) {
      errors.mobiledNumber = "This is not a valid email format!";
    }
    return errors;
  };







  const handleDownloadBrochure = () => {
    setIsModalOpen(true)
  }

  // const handleMenuClick = (sectionId) => {
  //   const section = document.getElementById(sectionId)
  //   if (section) {
  //     section.scrollIntoView({ behavior: "smooth" })
  //   }
  // }


  const handleSubmitd: React.FormEventHandler<HTMLFormElement> = async (e) => {
    e.preventDefault();
  
    // Set loading state
    setIsLoading(true);
  
    // Validate form values
    const errors = validated(formdValues);
    setFormdErrors(errors);
  
    if (Object.keys(errors).length === 0) {
      // If there are no errors, proceed with the submission
      setIsSubmitd(true);
  
      try {
        if (form.current) {

          await emailjs.sendForm('service_zxqe3ql', 'template_2jcvc7d', form.current, 'YPGH4Bt3T7bZH8HLb');
          console.log('SUCCESS!');
        
          // Simulate async operation (e.g., API call or file download)
          const pdfUrl = "/brochure1.pdf";
    
          // Simulate a delay for demonstration purposes
          await new Promise(resolve => setTimeout(resolve, 1000));
    
          // Save the brochure as a file
          saveAs(pdfUrl, 'brochure.pdf');
    
          // Reset form values
          setFormdValues({ mobiledNumber: '' });
    
          // Close the modal
          setIsModalOpen(false);
    
          // Optionally, show success notification
        }
        
      } catch (error) {
        console.error("Failed to download the brochure", error);
        // Optionally, handle error state
      }
    } else {
      // If there are errors, do not submit
      setIsSubmitd(false);
    }
  
    // Reset loading state
    setIsLoading(false);
  };

  return (
    
    <div className="flex flex-col min-h-dvh">
            <Navbar />
            {/* <WhatsAppFloatingIcon /> */}

      <main className="flex-1" style={{ marginTop: '80px' }}>
        <section className="section-with-bg-image w-full py-12 md:py-24 lg:py-20 text-primary-foreground">
          <div className="container px-4 md:px-6 grid gap-6 lg:grid-cols-2 lg:gap-12 items-center justify-center md:items-start">
            <div className="space-y-4 text-center md:text-left">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
                Master Data Analytics and Unlock Insights
              </h1>
              <p className="max-w-[600px] text-lg md:text-xl">
                Dive into the world of data analytics and gain the skills to transform raw data into actionable
                insights.
              </p>
              <div className="flex gap-4 justify-center md:justify-start">
                <Button
                  className="bg-blue hover:bg-primary-foreground/90 hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  onClick={() => setIsModalOpen(true)}
                >
                  <DownloadIcon className="w-5 h-5 mr-2" />
                  Download Brochure
                </Button>
              </div>
          {/* <p className="text-lg">info@insightsiq.org</p> */}

              <div className="flex">

    </div>
            </div>
            
            <div className="flex justify-center">
              {/* <div onSubmit={handleSubmit}> */}
              <Card className="w-full max-w-md">
      <CardHeader className="space-y-1">
        <CardTitle className="text-2xl">Enroll in the Course</CardTitle>
        <CardDescription>Fill out the form below to secure your spot.</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-4">
        <form ref={form} onSubmit={handleSubmit} className="space-y-4">
          <div className="grid gap-2">
            <div className="flex">
              <Label htmlFor="name" className="pr-2">Name</Label>
              <p className="text-red">{formErrors.name}</p>
            </div>
            <Input
              id="name"
              type="text"
              name="name"
              placeholder="Name"
              value={formValues.name}
              onChange={handleChange}
            />
          </div>
          <div className="grid gap-2">
            <div className="flex">
              <Label htmlFor="email" className="pr-2">Email</Label>
              <p className="text-red">{formErrors.email}</p>
            </div>
            <Input
              id="email"
              type="text"
              name="email"
              placeholder="Email"
              value={formValues.email}
              onChange={handleChange}
            />
          </div>
          <div className="grid gap-2">
            <div className="flex">
              <Label htmlFor="phone" className="pr-2">Mobile Number</Label>
              <p className="text-red">{formErrors.mobileNumber}</p>
            </div>
            <Input
              id="phone"
              type="tel"
              name="mobileNumber"
              placeholder="Mobile Number"
              value={formValues.mobileNumber}
              onChange={handleChange}
            />
          </div>
          <Button type="submit" className="w-full bg-blue text-primary-foreground hover:bg-primary focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50" disabled={isLoading}>
            {isLoading && <Loader />} {/* Show loader if isLoading is true */}
            {isLoading ? 'Processing...' : 'Enroll Now'}
          </Button>
        </form>

      </CardContent>
    </Card>
              
            </div>
          </div>
        </section>
        {/* <section className="w-full"> */}
        <section id="Why?" className="w-full py-12 md:py-24 lg:py-24 bg-muted lg:pl-36 ">
    <div className="space-y-12 y">
      <div className="text-center space-y-4">
        <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Why Choose Our Course?</h2>
        <p className="max-w-[700px] mx-auto text-muted-foreground md:text-xl">
          Unlock your potential with expert instruction, a comprehensive curriculum, and dedicated support for your career growth.
        </p>
      </div>
      <div className="relative overflow-hidden bg-white">
        <div className="flex space-x-6 overflow-x-auto pb-4 no-scrollbar snap-x snap-mandatory pl-4">
          <Card className="flex-shrink-0 w-[80%] sm:w-[calc(50%-1.5rem)] lg:w-[calc(33%-1.5rem)] snap-start">
            <CardHeader>
              <Image
                src="/insights-iq/hiring-process.png"
                width="100"
                height="100"
                alt="Technology Logo"
                className="aspect-square overflow-hidden rounded-lg object-contain object-center"
              />
            </CardHeader>
            <CardContent>
              <h3 className="text-lg font-bold">Mock Interviews</h3>
              <p className="text-muted-foreground">
                Get ready for real-world challenges with mock interviews by professionals, boosting your confidence and skills.
              </p>
            </CardContent>
          </Card>
          <Card className="flex-shrink-0 w-[80%] sm:w-[calc(50%-1.5rem)] lg:w-[calc(33%-1.5rem)] snap-start">
            <CardHeader>
              <Image
                src="/insights-iq/bank.png"
                width="100"
                height="100"
                alt="Technology Logo"
                className="aspect-square overflow-hidden rounded-lg object-contain object-center"
              />
            </CardHeader>
            <CardContent>
              <h3 className="text-lg font-bold">Learn from the Best</h3>
              <p className="text-muted-foreground">
                Learn from IIT Bombay graduates with top-tier expertise guiding you throughout your journey.
              </p>
            </CardContent>
          </Card>
          <Card className="flex-shrink-0 w-[80%] sm:w-[calc(50%-1.5rem)] lg:w-[calc(33%-1.5rem)] snap-start">
            <CardHeader>
              <Image
                src="/insights-iq/internship.png"
                width="100"
                height="100"
                alt="Internship Logo"
                className="aspect-square overflow-hidden rounded-lg object-contain object-center"
              />
            </CardHeader>
            <CardContent>
              <h3 className="text-lg font-bold">Internship Opportunities</h3>
              <p className="text-muted-foreground">
                Gain hands-on experience with guaranteed internships at top companies, preparing you for a successful career.
              </p>
            </CardContent>
          </Card>
          <Card className="flex-shrink-0 w-[80%] sm:w-[calc(50%-1.5rem)] lg:w-[calc(33%-1.5rem)] snap-start">
            <CardHeader>
              <Image
                src="/insights-iq/headhunting.png"
                width="100"
                height="100"
                alt="Placement Logo"
                className="aspect-square overflow-hidden rounded-lg object-contain object-center"
              />
            </CardHeader>
            <CardContent>
              <h3 className="text-lg font-bold">Placement Assurance</h3>
              <p className="text-muted-foreground">
                Secure your future with our placement assistance, ensuring you land a job at a leading company after graduation.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  </section>
{/* </section> */}


                <section id="Subjects" className="w-full py-12 md:py-24 lg:py-24">
          <div className="container px-4 md:px-6 space-y-12">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Academic Offerings</h2>
              <p className="max-w-[700px] mx-auto text-muted-foreground md:text-xl">
              The capstone course includes the following subjects
              </p>
            </div>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <Card>
              <CardHeader>
    <Image
      src="/insights-iq/Microsoft-Power-BI-Logo.png"
      width="140"
      height="140"
      alt="Technology Logo"
      className="aspect-square overflow-hidden rounded-lg object-contain object-center"
    />
  </CardHeader>
  <CardContent>
    <h3 className="text-lg font-bold">Power BI</h3>
    <p className="text-muted-foreground">
      Explore Microsofts Power BI, a comprehensive business intelligence and data visualization platform.
    </p>
  </CardContent>
</Card>

<Card>
  <CardHeader>
    <Image
      src="/insights-iq/PythonLogo.webp"
      width="140"
      height="140"
      alt="Technology Logo"
      className="aspect-square overflow-hidden rounded-lg object-contain object-center"
    />
  </CardHeader>
  <CardContent>
    <h3 className="text-lg font-bold">Python</h3>
    <p className="text-muted-foreground">
      Learn Python, a versatile and powerful programming language used for web development, data analysis, artificial intelligence, and more.
    </p>
  </CardContent>
</Card>

<Card>
  <CardHeader>
    <Image
      src="/insights-iq/excel-logo-0.png"
      width="140"
      height="140"
      alt="Technology Logo"
      className="aspect-square overflow-hidden rounded-lg object-contain object-center"
    />
  </CardHeader>
  <CardContent>
    <h3 className="text-lg font-bold">Excel</h3>
    <p className="text-muted-foreground">
      Master Excel, a powerful tool for data analysis, visualization, and spreadsheet management.
    </p>
  </CardContent>
</Card>

<Card>
  <CardHeader>
    <Image
      src="/insights-iq/Statistics.png"
      width="140"
      height="140"
      alt="Technology Logo"
      className="aspect-square overflow-hidden rounded-lg object-contain object-center"
    />
  </CardHeader>
  <CardContent>
    <h3 className="text-lg font-bold">Statistics</h3>
    <p className="text-muted-foreground">
      Understand Statistics, the science of collecting, analyzing, interpreting, and presenting data.
    </p>
  </CardContent>
</Card>
{/* 
<Card>
  <CardHeader>
    <Image
      src="/8345929.png"
      width="140"
      height="140"
      alt="Technology Logo"
      className="aspect-square overflow-hidden rounded-lg object-contain object-center"
    />
  </CardHeader>
  <CardContent>
    <h3 className="text-lg font-bold">Machine Learning</h3>
    <p className="text-muted-foreground">
      Dive into Machine Learning, a subset of AI that enables systems to learn from data and make decisions.
    </p>
  </CardContent>
</Card>

<Card>
  <CardHeader>
    <Image
      src="/artificial-intelligence.png"
      width="140"
      height="140"
      alt="Technology Logo"
      className="aspect-square overflow-hidden rounded-lg object-contain object-center"
    />
  </CardHeader>
  <CardContent>
    <h3 className="text-lg font-bold">Artificial Intelligence</h3>
    <p className="text-muted-foreground">
      Explore Artificial Intelligence, the simulation of human intelligence in machines.
    </p>
  </CardContent>
</Card> */}

<Card>
  <CardHeader>
    <Image
      src="/insights-iq/sql.png"
      width="140"
      height="140"
      alt="Technology Logo"
      className="aspect-square overflow-hidden rounded-lg object-contain object-center"
    />
  </CardHeader>
  <CardContent>
    <h3 className="text-lg font-bold">SQL</h3>
    <p className="text-muted-foreground">
      Learn SQL, a standard language for managing and manipulating databases.
    </p>
  </CardContent>
</Card>

<Card>
  <CardHeader>
    <Image
      src="/insights-iq/СhatGPT-Logo.png"
      width="140"
      height="140"
      alt="Technology Logo"
      className="aspect-square overflow-hidden rounded-lg object-contain object-center"
    />
  </CardHeader>
  <CardContent>
    <h3 className="text-lg font-bold">ChatGPT 4.0 and Dall-E</h3>
    <p className="text-muted-foreground">
      Discover ChatGPT 4.0 and Dall-E, advanced AI models for natural language processing and image generation, respectively.
    </p>
  </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section id="Overview" className="w-full py-12 md:py-24 lg:py-24 bg-muted">
          <div className="container px-4 md:px-6 space-y-12">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Course Overview</h2>
              <p className="max-w-[700px] mx-auto text-muted-foreground md:text-xl">
                Dive deep into the world of data analytics and learn how to transform raw data into actionable insights.
              </p>
            </div>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <DatabaseIcon className="w-8 h-8 text-blue" />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-bold">Data Fundamentals</h3>
                  <p className="text-muted-foreground">
                    Understand the core concepts of data, including data types, data structures, and data management.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <BarChartIcon className="w-8 h-8 text-blue" />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-bold">Data Analysis</h3>
                  <p className="text-muted-foreground">
                    Learn how to analyze data using various techniques, including statistical analysis, data
                    visualization, and machine learning.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CogIcon className="w-8 h-8 text-blue" />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-bold">Data Tools</h3>
                  <p className="text-muted-foreground">
                    Explore the most popular data analysis tools, including Excel, SQL, Python, and Tableau, and learn
                    how to use them effectively.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <PresentationIcon className="w-8 h-8 text-blue" />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-bold">Data Storytelling</h3>
                  <p className="text-muted-foreground">
                    Develop the skills to communicate your data insights effectively, using data visualization and
                    presentation techniques.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <PuzzleIcon className="w-8 h-8 text-blue" />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-bold">Real-World Projects</h3>
                  <p className="text-muted-foreground">
                    Apply your skills to real-world data analysis projects, working with industry-relevant datasets and
                    case studies.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <GraduationCapIcon className="w-8 h-8 text-blue" />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-bold">Certification</h3>
                  <p className="text-muted-foreground">
                    Earn a certificate of completion to showcase your data analytics skills and knowledge.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section id="Instructor" className="w-full py-12 md:py-24 lg:py-24">
          <div className="container px-4 md:px-6 space-y-12">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Meet Your Instructors</h2>
              <p className="max-w-[700px] mx-auto text-muted-foreground md:text-xl">
                Learn from industry experts with years of experience in data analytics.
              </p>
            </div>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <Image src="/insights-iq/3.jpg" width="200" height="200" alt="Instructor" className="rounded-full" />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-bold">Rushikesh Patil</h3>
                  <p className="text-muted-foreground">Data Scientist</p>
                  <p>
                  M.Tech IIT Bombay
                  </p>
                  <p>
                    Data Scientist at the Arena Group-USA
                  </p>
                  <p>
                  Oracle Database SQL Certified
                  </p>
                  <p>
                  Databricks Data Engineer Certified
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <Image src="/insights-iq/2.jpg" width="200" height="200" alt="Instructor" className="rounded-full" />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-bold">Kuldeep Kumar</h3>
                  <p className="text-muted-foreground">Data Scientist</p>
                  <p>
                  M.Tech IIT Bombay
                  </p>
                  <p>
                  Data Scientist at the Arena Group-USA
                  </p>
                  <p>
                  Oracle Database SQL Certified 
                  </p>
                  <p>
                  DBT Certified
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <Image src="/insights-iq/1.jpg" width="200" height="200" alt="Instructor" className="rounded-full" />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-bold">Md. Aquib</h3>
                  <p className="text-muted-foreground">Business Analyst</p>
                  <p>
                  M.Tech IIT Bombay
                  </p>
                  <p>
                  Business Analyst (Manager) Kotak Mahindra Bank
                  </p>
                  <p>
                  Subject Matter Expert- ChatGPT 4.0
                  </p>

                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <Image src="/insights-iq/5.jpg" width="200" height="200" alt="Instructor" className="rounded-full" />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-bold">Kritika Dwivedi</h3>
                  <p className="text-muted-foreground">Sr. Research Consultant</p>
                  <p>
                  M.Tech IIT Bombay
                  </p>
                  <p>
                  GISE Research Fellow
                  </p>
                  <p>
                  Min. of Women & Child Development Govt. of India
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <Image src="/insights-iq/4.jpg" width="200" height="200" alt="Instructor" className="rounded-full" />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-bold">Jayant Popli</h3>
                  <p className="text-muted-foreground">Sr. Research Consultant</p>
                  <p>
                  M.Tech IIT Bombay
                  </p>
                  <p>
                  UNICEF Research Fellow
                  </p>
                  <p>
                  Min. of Women & Child Development Govt. of India
                  </p>

                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section id="Partners" className="w-full py-12 md:py-24 lg:py-24 bg-muted">
          <div className="container px-4 md:px-6 space-y-12">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Partners</h2>
              <p className="max-w-[700px] mx-auto text-muted-foreground md:text-xl">
              We are proud to partner with leading organizations across various industries.
              </p>
            </div>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-5">
              <Card>
                <CardHeader>
                  <Image
                    src="/insights-iq/logo.png"
                    width="220"
                    height="220"
                    alt="Partner Logo"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                  />
                </CardHeader>
              </Card>
              <Card>
                <CardHeader>
                  <Image
                    src="/insights-iq/vision.png"
                    width="220"
                    height="220"
                    alt="Partner Logo"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                  />
                </CardHeader>
              </Card>
              <Card>
                <CardHeader>
                  <Image
                    src="/insights-iq/logo1.png"
                    width="220"
                    height="220"
                    alt="Partner Logo"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                  />
                </CardHeader>
              </Card>
              <Card>
                <CardHeader>
                  <Image
                    src="/insights-iq/tradEdge.png"
                    width="220"
                    height="220"
                    alt="Partner Logo"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                  />
                </CardHeader>
              </Card>
              <Card>
                <CardHeader>
                  <Image
                    src="/insights-iq/FM. Technologies.png"
                    width="220"
                    height="220"
                    alt="Partner Logo"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                  />
                </CardHeader>
              </Card>
            </div>
          </div>
        </section>
        <section id="FAQ" className="w-full py-12 md:py-24 lg:py-24">
          <div className="container px-4 md:px-6 space-y-12">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Frequently Asked Questions
              </h2>
              <p className="max-w-[700px] mx-auto text-muted-foreground md:text-xl">
                Get answers to common questions about the data analytics course.
              </p>
            </div>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <div className="space-y-2">
                <div className="flex items-center justify-between space-x-4 px-4">
                  <h4 className="text-sm font-semibold">What courses does your institute offer?</h4>
                  <div>
                    <Button variant="ghost" size="sm">
                    </Button>
                  </div>
                </div>
                <div className="rounded-md border px-4 py-2 font-mono text-sm shadow-sm">
                  We offer a capstone course name Data Analytics , It includes comprehensive range of sub-courses (Modules) in data science, including SQL, Excel, Python, Machine Learning, Artificial Intelligence, Power BI, ChatGPT 4.0.
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex items-center justify-between space-x-4 px-4">
                  <h4 className="text-sm font-semibold">Who are the instructors at your institute?</h4>
                  <div>
                    <Button variant="ghost" size="sm">
                    </Button>
                  </div>
                </div>
                <div className="rounded-md border px-4 py-2 font-mono text-sm shadow-sm">
                Our instructors are experienced professionals with M.Tech degrees from IIT Bombay and significant industry experience.
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex items-center justify-between space-x-4 px-4">
                  <h4 className="text-sm font-semibold">What qualifications do your instructors have?
                </h4>
                  <div>
                    <Button variant="ghost" size="sm">
                    </Button>
                  </div>
                </div>
                <div className="rounded-md border px-4 py-2 font-mono text-sm shadow-sm">
                Our instructors hold MTech degrees from IIT Bombay and have worked in top companies within the data science field.
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex items-center justify-between space-x-4 px-4">
                  <h4 className="text-sm font-semibold">What are the daily timings for your courses?
                  </h4>
                  <div>
                    <Button variant="ghost" size="sm">
                    </Button>
                  </div>
                </div>
                <div className="rounded-md border px-4 py-2 font-mono text-sm shadow-sm">
                Live sessions are typically scheduled during evenings from 8:00 PM to 9:00 PM daily including sundays, while recorded lectures can be accessed at any time for added flexibility.
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex items-center justify-between space-x-4 px-4">
                  <h4 className="text-sm font-semibold">What is the duration of course?and How are the course structured?
                  </h4>
                  <div>
                    <Button variant="ghost" size="sm">
                    </Button>
                  </div>
                </div>
                <div className="rounded-md border px-4 py-2 font-mono text-sm shadow-sm">
                The duration of this capstone course is of 4 Months, in whcih in first 3 months we focus on teaching and in last month we provide Intership opportunity.Our course are structured to provide a balance of theoretical knowledge and practical skills
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex items-center justify-between space-x-4 px-4">
                  <h4 className="text-sm font-semibold">Are there any prerequisites for enrolling in your courses?
                  </h4>
                  <div>
                    <Button variant="ghost" size="sm">
                    </Button>
                  </div>
                </div>
                <div className="rounded-md border px-4 py-2 font-mono text-sm shadow-sm">
                You can join with no prior knowldege in data science.
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <BackToTopButton />
      <WhatsAppFloatingIcon/>
      
      <footer className="w-full bg-muted text-muted-foreground py-6 px-4 md:px-6 footer">
        <div className="container flex flex-col items-center gap-4 md:flex-row md:justify-between">
          <p className="text-sm">&copy; 2024 InsightsIQ. All rights reserved.</p>
          <nav className="flex items-center gap-4">
            <Link href="/" className="text-sm hover:underline" prefetch={false}>
              Contact Us
            </Link>
          </nav>
        </div>
      </footer>
      <Dialog open={isModalOpen} onOpenChange={setIsModalOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Enter your mobile number</DialogTitle>
            <DialogDescription>Please enter your mobile number to download the brochure.</DialogDescription>
          </DialogHeader>
          <form ref={form} onSubmit={handleSubmitd} className="space-y-4">
          <div className="grid gap-2">
                 <div className="flex">
                 <Label htmlFor="phone" className="pr-2">Mobile Number</Label>
                 <p className="text-red">{formdErrors.mobiledNumber}</p>
                 </div>
                    <Input
                      id="phone"
                      type="tel"
                      name="mobiledNumber"
                      placeholder="mobileNumber"
                      value={formdValues.mobiledNumber}
                      onChange={handledChange}
                    />        
                  </div>
             <DialogFooter>
              <Button type="submit" className="bg-blue relative" disabled={isLoading}>
                {isLoading && <Loader />} {/* Show loader if isLoading is true */}
                {isLoading ? 'Processing...' : 'Download Brochure'}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  )
}

function BarChartIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}


function CogIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z" />
      <path d="M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
      <path d="M12 2v2" />
      <path d="M12 22v-2" />
      <path d="m17 20.66-1-1.73" />
      <path d="M11 10.27 7 3.34" />
      <path d="m20.66 17-1.73-1" />
      <path d="m3.34 7 1.73 1" />
      <path d="M14 12h8" />
      <path d="M2 12h2" />
      <path d="m20.66 7-1.73 1" />
      <path d="m3.34 17 1.73-1" />
      <path d="m17 3.34-1 1.73" />
      <path d="m11 13.73-4 6.93" />
    </svg>
  )
}


function DatabaseIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}


function DownloadIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}


function GraduationCapIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z" />
      <path d="M22 10v6" />
      <path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5" />
    </svg>
  )
}


function MenuIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function PresentationIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 3h20" />
      <path d="M21 3v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V3" />
      <path d="m7 21 5-5 5 5" />
    </svg>
  )
}


function PuzzleIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19.439 7.85c-.049.322.059.648.289.878l1.568 1.568c.47.47.706 1.087.706 1.704s-.235 1.233-.706 1.704l-1.611 1.611a.98.98 0 0 1-.837.276c-.47-.07-.802-.48-.968-.925a2.501 2.501 0 1 0-3.214 3.214c.446.166.855.497.925.968a.979.979 0 0 1-.276.837l-1.61 1.61a2.404 2.404 0 0 1-1.705.707 2.402 2.402 0 0 1-1.704-.706l-1.568-1.568a1.026 1.026 0 0 0-.877-.29c-.493.074-.84.504-1.02.968a2.5 2.5 0 1 1-3.237-3.237c.464-.18.894-.527.967-1.02a1.026 1.026 0 0 0-.289-.877l-1.568-1.568A2.402 2.402 0 0 1 1.998 12c0-.617.236-1.234.706-1.704L4.23 8.77c.24-.24.581-.353.917-.303.515.077.877.528 1.073 1.01a2.5 2.5 0 1 0 3.259-3.259c-.482-.196-.933-.558-1.01-1.073-.05-.336.062-.676.303-.917l1.525-1.525A2.402 2.402 0 0 1 12 1.998c.617 0 1.234.236 1.704.706l1.568 1.568c.23.23.556.338.877.29.493-.074.84-.504 1.02-.968a2.5 2.5 0 1 1 3.237 3.237c-.464.18-.894.527-.967 1.02Z" />
    </svg>
  )
}


function XIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
